### ISSUE TITLE
请问一下城市id是根据什么来定的

### ISSUE THREAD

**Issue by FlyToYourMooN** [JiahuaLink/TripStat#1]
为什么国内城市夹杂着国外城市，求教

**Comment by gaawal** [comment]
城市id可以通过F12查看   每个城市都不一样的，但是我没有遇到你说的国外夹杂的情况，可能携程最近又改了吧

**Comment by FlyToYourMooN** [comment]
谢谢你的爬虫，我爬了五千个城市并通过省市县表筛选出了中国城市，以此抓取景点更具体的信息，这对于我进一步的工作很有帮助！



---原始邮件---
发件人: "jiahua"<notifications@github.com&gt;
发送时间: 2020年12月1日(周二) 上午10:25
收件人: "JiahuaLink/TripStat"<TripStat@noreply.github.com&gt;;
抄送: "Biqigubafan"<97557509@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [JiahuaLink/TripStat] 请问一下城市id是根据什么来定的 (#1)




 
城市id可以通过F12查看   每个城市都不一样的，但是我没有遇到你说的国外夹杂的情况，可能携程最近又改了吧
